### ISSUE TITLE
Website interface and UX

### ISSUE THREAD

**Issue by st0yanov** [veskoy/ridiko#3]
**Gather ideas for the website's interface.**

- [x] Create a website logo
- [x] Choose a favicon
- [x] Choose a Page Cover for the Facebook page
- [x] Find a bootstrap template appropriate for the project's purpose

Note:
Upload images directly in this issue.

**Comment by denibeni** [comment]
![logo 4](https://user-images.githubusercontent.com/18089298/27762385-c8214d58-5e79-11e7-88c7-85dd5b79fb17.png)
This is the logo.

**Comment by edudev** [comment]
@deni-sl can you provide an image of the logo with a transparent background?
Maybe even one without the text?

**Comment by denibeni** [comment]
![facebook_messenger1600_favicon_logo](https://user-images.githubusercontent.com/18089298/27840392-32128b6c-6101-11e7-93b8-044409693f61.png)

**Comment by denibeni** [comment]
[favicon.zip](https://github.com/veskoy/ridiko/files/1122837/favicon.zip)
Favicon

**Comment by denibeni** [comment]
http://www.bootstrapzero.com/theme/landing-zero/
bootstrap template
