### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by st0yanov** [veskoy/ridiko#5]
**Design the platform database.**

- [x] Create database migrations
- [x] Create models

**Comment by edudev** [comment]
@veskoy does this look OK?

city can be postal code?

User:
    dateAdded (datetime)
    facebook account details (ids, hashes...)
    name
    phone
    profile

UserProfile:
    isDriver (yes/no)
    hasAirConditioning (yes/no)
    prefersAirConditioning (yes/no)
    isSmoking (yes/no)
    isTolerantToSmoking (yes/no)
    isTolerantToPets (yes/no)
    isTolerantToEating (yes/no)

Trip:
    dateAdded (datetime)
    dateDropped (datetime)
    organizer (user)
    source (city, string)
    startTime (datetime)
    destination (city, string)
    freeSeats (number)

UserToUserRating
    trip
    dateRated (datetime)
    rater (user)
    rated (user)
    isRatedOrganizer (yes/no)
    rating (1-5)
    comment (text)

UserTripMapping:
    dateMapped (datetime)
    dateDropped (datetime)
    user
    trip
    willBringPets (yes/no)


TripSearch:
    dateStarted (datetime)
    dateDropped (datetime)
    user
    destination (city, string)

**Comment by st0yanov** [comment]
Excellent! What about trip free seats?

The flow mockup might be helpful:
https://github.com/veskoy/ridiko/issues/6#issuecomment-312432195

**Comment by st0yanov** [comment]
It will be nice to have those for the trip preferences:
- isEatingAllowed (eating in the vehicle)
- hasAirConditioning (boolean)
- luggageSpace (low/medium/high) <- (or maybe we should omit this)

**Comment by edudev** [comment]
@veskoy I've changed preferences to UserInfo. I've added a field to tell whether the person is a driver (not really sure if it will be of help, maybe just for asking the right questions). I've added fields to eating tolerancy and air conditioning preferences/availability.
About the luggage: I think it's hard to estimate.

**Comment by st0yanov** [comment]
Some additions:
Drivers have one car (string).
Trips have breaks (boolean).

Related to the driver flow:
https://github.com/veskoy/ridiko/issues/6#issuecomment-312434253
